platform :ios, '10.0'
use_frameworks!

target 'Convos' do
  pod 'Alamofire', '~> 4.5.1'
  pod 'AlamofireImage', '~> 3.3'
  pod 'SwiftWebSocket', '~> 2.6.5'
  pod 'SQLite.swift', '~> 0.11.3'
  pod 'SwiftyJSON', '~> 3.1.4'
  pod 'SwiftyGif', '~> 3.1.0'
  pod 'Auth0', '~> 1.0'
end
